<?php 
    $list = $block->getQuestion();
    if(count($list)>0):
?>
<style>
    #slideshow {
        margin: 50px auto;
        position: relative;
        width: 440px;
        height: 200px;
        padding: 10px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.4);
    }

    #slideshow>div {
        position: absolute;
        top: 10px;
        left: 10px;
        right: 10px;
        bottom: 10px;
    }
</style>
<div id="slideshow">
    <?php foreach ($list as $question):?>
    <div>
        <h3>Question From: <?=$question->getC_name()?> For Product <?=$question->getP_name()?></h3>
        <p><?=$question->getContent()?></p>
        <h3>Answer From Admin:</h3>
        <p><?=$question->getAnswer()?></p>
    </div>
    <?php endforeach;?>
   
</div>

<script>
    require(['jquery', 'jquery/ui'], function($) {
        $("#slideshow > div:gt(0)").hide();

        setInterval(function() {
            $('#slideshow > div:first')
                .delay(2000)
                .fadeOut(2000)
                .next()
                .delay(2000)
                .fadeIn(2000)
                .end()
                .appendTo('#slideshow');
        }, 6000);
    });
</script>
 <?php endif;?>