<?php
$list = $block->getQuestion(); 
if($list!=null):
?>
  
   <div class="question-list" style="margin-top: 50px; margin-bottom:50px; border: 1px solid black; padding: 10px">
    <div class="title" style="font-weight:bold">
        List question for this product
    </div>
    <div class="list">
            <?php foreach ($list as $a):?>
        <?php $id = $a->getCustomer_id();
            $customer = $block->getCustomer($id);        
        ?>
        <div class="customer-name"><b>Question from:</b> <?php echo $customer->getFirstname()." ".$customer->getMiddlename()." ".$customer->getLastname() ;?></div>
        <div class="content"><?php echo $a->getContent();?></div>
        <p><b>Answer From Admin:</b> <?=$a->getAnswer()?></p>
        <br>
        <?php endforeach;?>
    </div>
    </div>
<?php endif;?>